version: "3.7"
services:
  react:
    build:
      args:
        - NODE_VER=20.12.0
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app_node_modules
    ports:
      - 3000:3000
volumes:
  node_modules: