import Head from "next/head";
import Clock from "./_components/Clock";
import Today from "./_components/Today";
import { Button } from "../components/ui/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center">
        <div className="lx:gap-20 flex flex-col gap-6 sm:gap-8 md:gap-8 lg:gap-16">
          <Today />
          <Clock />
          <Button>Click me</Button>
        </div>
      </main>
    </>
  );
}
