import Head from "next/head";
import Clock from "./_components/Clock";
import Today from "./_components/Today";
import { ModeToggle } from "./_components/DarkMode";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center bg-gradient-to-b from-gray-100 to-white dark:from-gray-800 dark:to-gray-900">
        <div className="mx:right-10 absolute right-5 top-10 flex gap-2 lg:right-20 ">
          <ModeToggle />
        </div>
        <div className="lx:gap-20 flex flex-col gap-6 sm:gap-8 md:gap-8 lg:gap-16">
          <Today />
          <Clock />
        </div>
      </div>
    </>
  );
}
